#!/bin/bash
#
# On 2025-10-13, the deployment was using v1.127.0 (before pt-index).
# Queries must return full results.

BASE_URL=http://localhost:8481/select/0/prometheus
START=2025-10-13T00:01:00
END=2025-10-13T23:59:59

curl ${BASE_URL}/api/v1/series -d 'match[]=up' -d "start=${START}" -d "end=${END}"
echo
curl ${BASE_URL}/api/v1/labels -d 'match[]=up' -d "start=${START}" -d "end=${END}"
echo
curl ${BASE_URL}/api/v1/label/node/values -d 'match[]=up' -d "start=${START}" -d "end=${END}"
echo
curl ${BASE_URL}/api/v1/query_range -d 'query=count(up)' -d "start=${START}" -d "end=${END}" -d "step=1h"
