#!/bin/bash
#
# On 2025-10-14, the deployment was using pt-index.
# After downgrading the deployment, the queries should return partial or no
# results. After upgrading again, the queries must return full results again.

BASE_URL=http://localhost:8481/select/0/prometheus
START=2025-10-14T00:01:00
END=2025-10-14T23:59:59

curl ${BASE_URL}/api/v1/series -d 'match[]=up' -d "start=${START}" -d "end=${END}"
echo
curl ${BASE_URL}/api/v1/labels -d 'match[]=up' -d "start=${START}" -d "end=${END}"
echo
curl ${BASE_URL}/api/v1/label/node/values -d 'match[]=up' -d "start=${START}" -d "end=${END}"
echo
curl ${BASE_URL}/api/v1/query_range -d 'query=count(up)' -d "start=${START}" -d "end=${END}" -d "step=1h"
