apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: benchmark-vm-cluster-7599
  namespace: rtm0-test
spec:
  retentionPeriod: "6"
  replicationFactor: 2
  clusterVersion: "v1.126.0-enterprise-cluster"
  license:
    keyRef:
      key: license
      name: vm-license
  vminsert:
    replicaCount: 1
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: "1"
        memory: 500Mi
      limits:
        cpu: "1"
        memory: 500Mi
  vmselect:
    replicaCount: 2
    image:
      pullPolicy: "Always"
    extraArgs:
      search.maxQueryDuration: "600s"
      search.logSlowQueryDuration: "30s"
      search.logSlowQueryStats: "1us"
      dedup.minScrapeInterval: "1ms"
      "downsampling.period": '5d:10m,30d:30m,{__name__="up"}:40d:1h'
    resources:
      requests:
        cpu: "2"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 1Gi
  vmstorage:
    replicaCount: 4
    rollingUpdateStrategyBehavior:
      maxUnavailable: 100%
    image:
      tag: heads-issue-7599-enterprise-cluster-0-g879ec9d5dc
      pullPolicy: Always
    extraArgs:
      retentionFilter: '{instance=~"host-(0|1)"}:10d'
      dedup.minScrapeInterval: "1ms"
      "storage.trackMetricNamesStats": "true"
      "downsampling.period": '5d:10m,30d:30m,{__name__="up"}:40d:1h'
    resources:
      requests:
        cpu: "2"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 200Gi
          storageClassName: standard-rwo
  requestsLoadBalancer:
    enabled: true
    spec:
      image:
        pullPolicy: "Always"
        tag: "v1.126.0-enterprise"
