apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: gh10064
  namespace: gh10064
spec:
  retentionPeriod: "6"
  replicationFactor: 1
  clusterVersion: "v1.131.0-cluster"
  vminsert:
    replicaCount: 1
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
  vmselect:
    replicaCount: 2
    image:
      pullPolicy: "Always"
    extraArgs:
      search.logSlowQueryDuration: 15s
    resources:
      requests:
        cpu: "3"
        memory: 12Gi
      limits:
        cpu: "3"
        memory: 12Gi
  vmstorage:
    replicaCount: 4
    rollingUpdateStrategyBehavior:
      maxUnavailable: 100%
    image:
      pullPolicy: Always
    extraArgs:
      memory.allowedPercent: "50"
      precisionBits: "64"
    resources:
      requests:
        cpu: "4"
        memory: 16Gi
      limits:
        cpu: "4"
        memory: 16Gi
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 200Gi
          storageClassName: standard-rwo
  requestsLoadBalancer:
    enabled: true
    spec:
      image:
        pullPolicy: "Always"
        tag: "v1.131.0"
