apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: default
  namespace: default
spec:
  retentionPeriod: "6"
  replicationFactor: 1
  clusterVersion: "v1.132.0-enterprise-cluster"
  license:
    keyRef:
      key: license
      name: vm-license
  vminsert:
    replicaCount: 2
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: "2"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 1Gi
  vmselect:
    replicaCount: 2
    image:
      pullPolicy: "Always"
    extraArgs:
      search.logSlowQueryDuration: 15s
      search.logSlowQueryStats: 15s
    resources:
      requests:
        cpu: "4"
        memory: 8Gi
      limits:
        cpu: "4"
        memory: 8Gi
  vmstorage:
    replicaCount: 2
    rollingUpdateStrategyBehavior:
      maxUnavailable: 100%
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: "8"
        memory: 32Gi
      limits:
        cpu: "8"
        memory: 32Gi
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 200Gi
          storageClassName: standard-rwo
  requestsLoadBalancer:
    enabled: true
    spec:
      image:
        pullPolicy: "Always"
        tag: "v1.132.0-enterprise"
