apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: rtm0-perf
  namespace: rtm0-perf
spec:
  retentionPeriod: "6"
  replicationFactor: 1
  clusterVersion: "v1.128.0-enterprise-cluster"
  license:
    keyRef:
      key: license
      name: vm-license
  vminsert:
    replicaCount: 1
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
  vmselect:
    replicaCount: 2
    image:
      pullPolicy: "Always"
    resources:
      requests:
        cpu: 2000m
        memory: 8Gi
      limits:
        cpu: 2000
        memory: 8Gi
  vmstorage:
    replicaCount: 4
    rollingUpdateStrategyBehavior:
      maxUnavailable: 25%
    image:
      # tag: heads-issue-7599-enterprise-cluster-0-g7356c81f89
      pullPolicy: Always
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 4000m
        memory: 8Gi
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 200Gi
          storageClassName: standard-rwo
  requestsLoadBalancer:
    enabled: true
    spec:
      image:
        pullPolicy: "Always"
        tag: "v1.128.0-enterprise"
