apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: rtm0-perf
  namespace: rtm0-perf
spec:
  retentionPeriod: "6"
  replicationFactor: 1
  clusterVersion: "v1.128.0-cluster"
  vminsert:
    replicaCount: 1
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: "1"
        memory: 500Mi
      limits:
        cpu: "1"
        memory: 500Mi
  vmselect:
    replicaCount: 2
    image:
      pullPolicy: "Always"
    resources:
      requests:
        cpu: "2"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 1Gi
  vmstorage:
    replicaCount: 4
    rollingUpdateStrategyBehavior:
      maxUnavailable: 100%
    image:
      # tag: heads-issue-7599-enterprise-cluster-0-gc94c7bf55c
      pullPolicy: Always
    resources:
      requests:
        cpu: "2"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 200Gi
          storageClassName: standard-rwo
  requestsLoadBalancer:
    enabled: true
    spec:
      image:
        pullPolicy: "Always"
        tag: "v1.128.0"
