apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: rtm0-perf
  namespace: rtm0-perf
spec:
  license:
    keyRef:
      key: license
      name: vm-license
  image:
    tag: v1.128.0-enterprise
  retentionPeriod: "6"
  removePvcAfterDelete: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  extraArgs:
    dedup.minScrapeInterval: 60s
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 1000m