#!/bin/bash

if [[ $# -lt 1 ]]
then
	echo -e "Usage:\n\t$(basename $0) NAME [COUNT]"
	exit 1
fi

NAME=$1
COUNT=${2:-10}
PREFIX=${NAME}-count${COUNT}

BENCHMARKS=(
  BenchmarkStorageAddRows \
  BenchmarkStorageAddRows_VariousTimeRanges \
  BenchmarkStorageInsertWithAndWithoutPerDayIndex \
  BenchmarkSearchData_variableSeries \
  BenchmarkSearchData_variableDeletedSeries \
  BenchmarkSearchData_variableTimeRange \
  BenchmarkSearchMetricNames_variableSeries \
  BenchmarkSearchMetricNames_variableDeletedSeries \
  BenchmarkSearchMetricNames_variableTimeRange \
  BenchmarkSearchLabelNames_variableSeries \
  BenchmarkSearchLabelNames_variableDeletedSeries \
  BenchmarkSearchLabelNames_variableTimeRange \
  BenchmarkSearchLabelValues_variableSeries \
  BenchmarkSearchLabelValues_variableDeletedSeries \
  BenchmarkSearchLabelValues_variableTimeRange \
  BenchmarkSearchTagValueSuffixes_variableSeries \
  BenchmarkSearchTagValueSuffixes_variableDeletedSeries \
  BenchmarkSearchTagValueSuffixes_variableTimeRange \
  BenchmarkSearchGraphitePaths_variableSeries \
  BenchmarkSearchGraphitePaths_variableDeletedSeries \
  BenchmarkSearchGraphitePaths_variableTimeRange
)

for b in "${BENCHMARKS[@]}"
do
  SUFFIX=$(echo ${b} | sed 's|/|-|g')

  LOGFILE=~/${PREFIX}-${SUFFIX}.log
  CPUFILE=~/${PREFIX}-${SUFFIX}-cpu.pprof
  MEMFILE=~/${PREFIX}-${SUFFIX}-mem.pprof
  MUTEXFILE=~/${PREFIX}-${SUFFIX}-mutex.pprof
  BLOCKFILE=~/${PREFIX}-${SUFFIX}-block.pprof

  go test ./lib/storage -run="^$" \
    -bench="^${b}$" \
    -count=${COUNT} \
    -timeout=48h \
    -benchmem \
    -cpuprofile=${CPUFILE} \
    -memprofile=${MEMFILE} \
    -mutexprofile=${MUTEXFILE} \
    -blockprofile=${BLOCKFILE} \
    --loggerLevel=ERROR \
    | tee ${LOGFILE}

  echo -e "\n\n" >> ${LOGFILE}
  echo
  echo ${LOGFILE}
  echo ${CPUFILE}
  echo ${MEMFILE}
  echo ${MUTEXFILE}
  echo ${BLOCKFILE}
  echo
done

COMBINED_LOGFILE=~/${PREFIX}.log
rm -f ${COMBINED_LOGFILE}
cat ~/${PREFIX}-*.log >> ${COMBINED_LOGFILE}
echo
echo ${PREFIX}=${COMBINED_LOGFILE}
echo
