#!/bin/bash

BASEDIR=$(realpath $(dirname $0))
source ${BASEDIR}/vm-libbranch

# Also sets up ${OSS_SINGLE_BRANCH}
git clone git@github.com:VictoriaMetrics/VictoriaMetrics.git src
cd src

git remote add enterprise git@github.com:VictoriaMetrics/VictoriaMetrics-enterprise.git
git remote add tigo git@github.com:tIGO/VictoriaMetrics.git

git fetch --all --tags

git checkout --track ${OSS_SINGLE_REMOTE}/${OSS_SINGLE_BRANCH}
git checkout --track ${OSS_CLUSTER_REMOTE}/${OSS_CLUSTER_BRANCH}
git checkout --track ${ENT_SINGLE_REMOTE}/${ENT_SINGLE_BRANCH}
git checkout --track ${ENT_CLUSTER_REMOTE}/${ENT_CLUSTER_BRANCH}
git checkout --track ${LTS1_SINGLE_REMOTE}/${LTS1_SINGLE_BRANCH}
git checkout --track ${LTS1_CLUSTER_REMOTE}/${LTS1_CLUSTER_BRANCH}
git checkout --track ${LTS2_SINGLE_REMOTE}/${LTS2_SINGLE_BRANCH}
git checkout --track ${LTS2_CLUSTER_REMOTE}/${LTS2_CLUSTER_BRANCH}
git checkout --track ${PMM_SINGLE_REMOTE}/${PMM_SINGLE_BRANCH}
git checkout --track ${BMC_CLUSTER_REMOTE}/${BMC_CLUSTER_BRANCH}

git switch ${OSS_SINGLE_BRANCH}
