#!/bin/bash

if [[ $# -lt 1 ]]
then
	echo -e "Usage:\n\t$(basename $0) NAME [COUNT]"
	exit 1
fi

NAME=$1
COUNT=${2:-10}
PREFIX=${NAME}-count${COUNT}

BENCHMARKS=(
  BenchmarkStorageAddRows \
  BenchmarkStorageAddRows_VariousTimeRanges \
  BenchmarkStorageInsertWithAndWithoutPerDayIndex \
  BenchmarkStorageSearchMetricNames_VariousTimeRanges \
  BenchmarkStorageSearchLabelNames_VariousTimeRanges \
  BenchmarkStorageSearchLabelValues_VariousTimeRanges \
  BenchmarkStorageSearchTagValueSuffixes_VariousTimeRanges \
  BenchmarkStorageSearchGraphitePaths_VariousTimeRanges \
  BenchmarkSearch_VariousTimeRanges
)

for b in "${BENCHMARKS[@]}"
do
  SUFFIX=$(echo ${b} | sed 's|/|-|g')
  LOGFILE=~/${PREFIX}-${SUFFIX}.log
  CPUFILE=~/${PREFIX}-${SUFFIX}.cpuprofile
  go test ./lib/storage -run="^$" \
    -bench="^${b}$" \
    -count=${COUNT} \
	-timeout=48h \
	-benchmem \
    -cpuprofile ${CPUFILE} \
    --loggerLevel=ERROR \
    | tee ${LOGFILE}

  echo -e "\n\n" >> ${LOGFILE}
  echo
  echo ${LOGFILE}
  echo ${CPUFILE}
  echo
done

COMBINED_LOGFILE=~/${PREFIX}.log
rm -f ${COMBINED_LOGFILE}
cat ~/${PREFIX}-*.log >> ${COMBINED_LOGFILE}
echo
echo ${PREFIX}=${COMBINED_LOGFILE}
echo
