#!/bin/bash

if [[ $# -ne 1 ]]
then
	echo -e "Usage:\n\t$(basename $0) EMAIL"
	exit 1
fi

EMAIL=$1

ssh-keygen -t ed25519 -C "${EMAIL}"
echo
echo
echo "Add the following public key at https://github.com/settings/keys"
echo
cat ~/.ssh/id_ed25519.pub
echo
echo
