#!/bin/bash

BASEDIR=$(dirname $(realpath $0))
INSTANCE=$1
ZONE=$2

gcloud compute scp ${BASEDIR}/vm-keygen ${INSTANCE}:vm-keygen --zone=${ZONE}
gcloud compute scp ${BASEDIR}/vm-keyadd ${INSTANCE}:vm-keyadd --zone=${ZONE}
