#!/bin/bash

if [[ $# -ne 1 ]]
then
	echo -e "Usage:\n\t$(basename $0) ZONE"
	exit 1
fi
ZONE=$1

gcloud compute zones describe ${ZONE} --format="value(availableCpuPlatforms)"
echo
echo "Docs: https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform#how_selecting_a_minimum_cpu_platform_works"