#!/bin/bash

apt update

# Add Docker's official GPG key:
apt install ca-certificates curl
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null
apt update

apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
apt install -y tmux emacs-nox git make gcc

test -f /usr/local/go/bin/go || (\
  wget https://go.dev/dl/go1.24.4.linux-amd64.tar.gz && \
  rm -rf /usr/local/go && \
  tar -C /usr/local -xzf go1.24.4.linux-amd64.tar.gz)
grep -q 'export PATH=$PATH:/usr/local/go/bin' /etc/bash.bashrc || \
  echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/bash.bashrc
