#!/bin/bash

BASEDIR=$(dirname $(realpath $0))
INSTANCE=${1:-rtm0-$(date +%s)}
MACHINE_TYPE=${2:-e2-standard-8}
ZONE=${3:-europe-west10-a}
STARTUP_SCRIPT=${BASEDIR}/vm-vm-startup-script

gcloud compute instances create ${INSTANCE} \
  --machine-type=${MACHINE_TYPE} \
  --zone=${ZONE} \
  --create-disk=auto-delete=yes,boot=yes,device-name=${INSTANCE},mode=rw,size=100,type=pd-balanced,image=projects/debian-cloud/global/images/debian-12-bookworm-v20250709 \
  --metadata-from-file=startup-script=${STARTUP_SCRIPT} \
  --quiet
