apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-benchmark-7599
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: rtm0-test
  project: default
  source:
    path: chart
    repoURL: "https://github.com/VictoriaMetrics/prometheus-benchmark"
    targetRevision: main
    helm:
      valuesObject:
        vmtag: "v1.119.0"
        disableMonitoring: true
        targetsCount: 2000
        scrapeInterval: 20s
        queryInterval: 10s
        scrapeConfigUpdatePercent: 1
        scrapeConfigUpdateInterval: 10m
        writeConcurrency: 16
        remoteStorages:
          vm:
            writeURL: "http://vminsert-benchmark-vm-cluster-7599.rtm0-test:8480/insert/0/prometheus/"
            readURL: "http://vmselect-benchmark-vm-cluster-7599.rtm0-test:8481/select/0/prometheus"
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
