apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: benchmark-vmagent-collect
  namespace: gh10297
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
  selector:
    matchLabels:
      job: vmagent
      remote-storage-name: vm