apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: gh10297
  namespace: gh10297
spec:
  retentionPeriod: "3"
  replicationFactor: 1
  clusterVersion: "v1.129.1-cluster"
  vminsert:
    replicaCount: 10
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
  vmselect:
    replicaCount: 7
    image:
      pullPolicy: "Always"
    resources:
      requests:
        cpu: "2"
        memory: 8Gi
      limits:
        cpu: "2"
        memory: 8Gi
  vmstorage:
    replicaCount: 2
    rollingUpdateStrategyBehavior:
      maxUnavailable: 100%
    image:
      tag: v1.129.1-cluster
      pullPolicy: Always
    resources:
      requests:
        cpu: "5"
        memory: 30Gi
      limits:
        cpu: "6"
        memory: 50Gi
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 500Gi
          storageClassName: standard-rwo
  requestsLoadBalancer:
    enabled: true
    spec:
      image:
        pullPolicy: "Always"
        tag: "v1.129.1"
