apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: pt-index
  namespace: pt-index
spec:
  retentionPeriod: "6"
  replicationFactor: 1
  clusterVersion: "v1.132.0-enterprise-cluster"
  license:
    keyRef:
      key: license
      name: vm-license
  vminsert:
    replicaCount: 2
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: "2"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 1Gi
  vmselect:
    replicaCount: 2
    image:
      pullPolicy: "Always"
    extraArgs:
      search.logSlowQueryDuration: 5m
      search.logSlowQueryStats: 5m
      search.maxQueryDuration: 5m
    resources:
      requests:
        cpu: "4"
        memory: 8Gi
      limits:
        cpu: "4"
        memory: 8Gi
  vmstorage:
    replicaCount: 2
    rollingUpdateStrategyBehavior:
      maxUnavailable: 100%
    image:
      tag: heads-enterprise-cluster-0-g0d65f26545
      pullPolicy: Always
    extraArgs:
      storage.cacheSizeIndexDBTagFilters: 4GiB
    resources:
      requests:
        cpu: "12"
        memory: 48Gi
      limits:
        cpu: "12"
        memory: 48Gi
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1000Gi
          storageClassName: standard-rwo
  requestsLoadBalancer:
    enabled: true
    spec:
      image:
        pullPolicy: "Always"
        tag: "v1.132.0-enterprise"
